// Store action types as constants for easy modification in the future

export const FETCH_LISTS_REQUEST = "FETCH_LISTS_REQUEST";
export const FETCH_LISTS_FAILURE = "FETCH_LISTS_FAILURE";
export const FETCH_LISTS_SUCCESS = "FETCH_LISTS_SUCCESS";

export const CREATE_LIST_REQUEST = "CREATE_LIST_REQUEST";
export const CREATE_LIST_FAILURE = "CREATE_LIST_FAILURE";
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const EDIT_LIST_REQUEST = "EDIT_LIST_REQUEST";
export const EDIT_LIST_FAILURE = "EDIT_LIST_FAILURE";
export const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS";

export const ADD_TO_LIST_REQUEST = "ADD_TO_LIST_REQUEST";
export const ADD_TO_LIST_FAILURE = "ADD_TO_LIST_FAILURE";
export const ADD_TO_LIST_SUCCESS = "ADD_TO_LIST_SUCCESS";

export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const DELETE_LIST_FAILURE = "DELETE_LIST_FAILURE";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";

export const EDIT_LIST_ITEM_REQUEST = "EDIT_LIST_ITEM_REQUEST";
export const EDIT_LIST_ITEM_FAILURE = "EDIT_LIST_ITEM_FAILURE";
export const EDIT_LIST_ITEM_SUCCESS = "EDIT_LIST_ITEM_SUCCESS";

export const FETCH_LIST_ITEMS_REQUEST = "FETCH_LIST_ITEMS_REQUEST";
export const FETCH_LIST_ITEMS_FAILURE = "FETCH_LIST_ITEMS_FAILURE";
export const FETCH_LIST_ITEMS_SUCCESS = "FETCH_LIST_ITEMS_SUCCESS";

export const DELETE_LIST_ITEM_REQUEST = "DELETE_LIST_ITEM_REQUEST";
export const DELETE_LIST_ITEM_FAILURE = "DELETE_LIST_ITEM_FAILURE";
export const DELETE_LIST_ITEM_SUCCESS = "DELETE_LIST_ITEM_SUCCESS";

// Authentication

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
